In [2]:
import numpy as np
import pandas as pd
# We want to see whole content (non-truncated)
#pd.set_option('display.max_colwidth', None)

In [6]:
# Load the tweets
lms = pd.read_csv("studentFeebackOnServicesLMS_wlabel.csv")

course= pd.read_csv("studentFeedbackCourses_wlabel.csv")
# Print the first five rows
display(lms.head(10))
display(course.head(10))

,Unnamed: 0,Content,Processed,Polarity,Subjectivity,Label
0,0,Display is excellent and camera is as good as ...,"['display', 'excellent', 'camera', 'good', 'ye...",8.500000e-01,0.800000,Positive
1,1,Battery life is also great!,"['battery', 'life', 'also', 'great']",8.000000e-01,0.750000,Positive
2,2,Protects the phone on all sides.,"['protects', 'phone', 'sides']",0.000000e+00,0.000000,Neutral
3,3,"Clear Skype Calls, Long Battery Life, Long Range.","['clear', 'skype', 'calls', 'long', 'battery',...",4.625929e-18,0.394444,Positive
4,4,Great Hands Free Device.,"['great', 'hands', 'free', 'device']",6.000000e-01,0.775000,Positive
5,5,you can even take self portraits with the outs...,"['even', 'take', 'self', 'portraits', 'outside...",1.750000e-01,0.350000,Positive
6,6,After trying many many handsfree gadgets this ...,"['trying', 'many', 'many', 'handsfree', 'gadge...",3.333333e-01,0.666667,Positive
7,7,Magical Help.,"['magical', 'help']",5.000000e-01,1.000000,Positive
8,8,The best phone in market :).,"['best', 'phone', 'market']",1.000000e+00,0.300000,Positive
9,9,It worked very well.,"['worked', 'well']",0.000000e+00,0.000000,Neutral

,Unnamed: 0,Content,Processed,Polarity,Subjectivity,Label
0,0,good and interesting,"['good', 'interesting']",0.600000,0.550000,Positive
1,1,"This class is very helpful to me. Currently, I...","['class', 'helpful', 'currently', 'still', 'le...",0.000000,0.262500,Neutral
2,2,like!Prof and TAs are helpful and the discussi...,"['like', 'prof', 'tas', 'helpful', 'discussion...",0.183333,0.800000,Positive
3,3,Easy to follow and includes a lot basic and im...,"['easy', 'follow', 'includes', 'lot', 'basic',...",0.277778,0.652778,Positive
4,4,Really nice teacher!I could got the point eazl...,"['really', 'nice', 'teacher', 'could', 'got', ...",0.600000,1.000000,Positive
5,5,"Great course - I recommend it for all, especia...","['great', 'course', 'recommend', 'especially',...",0.400000,0.875000,Positive
6,6,One of the most useful course on IT Management!,"['one', 'useful', 'course', 'management']",0.300000,0.000000,Positive
7,7,I was disappointed because the name is mislead...,"['disappointed', 'name', 'misleading', 'course...",0.065551,0.449702,Positive
8,8,Super content. I'll definitely re-do the course,"['super', 'content', 'definitely', 'course']",0.166667,0.583333,Positive
9,9,One of the excellent courses at Coursera for i...,"['one', 'excellent', 'courses', 'coursera', 'i...",1.000000,1.000000,Positive

In [15]:
# We do not need first two columns. Let's drop them out.
lms.drop(columns=["Processed","Polarity", "Subjectivity"], axis=1, inplace=True)
course.drop(columns=["Processed","Polarity", "Subjectivity"], axis=1, inplace=True)
# Drop duplicated rows
lms.drop_duplicates(inplace=True)
course.drop_duplicates(inplace=True)
# Created at column's type should be datatime
#tweets_raw["Created at"] = pd.to_datetime(tweets_raw["Created at"])

In [16]:
# Print the first five rows
display(lms.head())
display(course.head())

                                             Content     Label
0  Display is excellent and camera is as good as ...  Positive
1                        Battery life is also great!  Positive
2                   Protects the phone on all sides.   Neutral
3  Clear Skype Calls, Long Battery Life, Long Range.  Positive
4                           Great Hands Free Device.  Positive

                                             Content     Label
0                               good and interesting  Positive
1  This class is very helpful to me. Currently, I...   Neutral
2  like!Prof and TAs are helpful and the discussi...  Positive
3  Easy to follow and includes a lot basic and im...  Positive
4  Really nice teacher!I could got the point eazl...  Positive

In [17]:
# Save the processed data as a csv file
lms.to_csv("studentFeebackOnServicesLMS_wlabel_final.csv", index=False)
course.to_csv("studentFeedbackCourses_wlabel_final.csv", index=False)